package me.drton.jmavsim;

import com.sun.j3d.exp.swing.JCanvas3D;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by admin on 5/2/2014.
 */
public class MainWindow {
    JFrame frame;
    public JPanel panel1;
    private JButton btn_Start;
    public JCanvas3D canvas3D = new JCanvas3D();
    private JButton btn_Stop;
    private JButton xButton;
    private JButton xButton1;
    private JButton yButton;
    private JButton yButton1;

    public MainWindow(ActionListener uiCommandListener) {
        frame = new JFrame("Mav Simulator");
        $$$setupUI$$$();
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        btn_Start.addActionListener(uiCommandListener);
        btn_Stop.addActionListener(uiCommandListener);
        xButton.addActionListener(uiCommandListener);
        xButton1.addActionListener(uiCommandListener);
        yButton.addActionListener(uiCommandListener);
        yButton1.addActionListener(uiCommandListener);
    }

    public void show() {
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setPreferredSize(new Dimension(600, 400));
        panel1.setRequestFocusEnabled(true);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel2.setEnabled(false);
        panel1.add(panel2, BorderLayout.NORTH);
        btn_Start = new JButton();
        btn_Start.setActionCommand("start");
        btn_Start.setHorizontalAlignment(2);
        btn_Start.setText("Start");
        panel2.add(btn_Start);
        btn_Stop = new JButton();
        btn_Stop.setActionCommand("stop");
        btn_Stop.setText("Stop");
        panel2.add(btn_Stop);
        xButton = new JButton();
        xButton.setText("X");
        panel2.add(xButton);
        xButton1 = new JButton();
        xButton1.setText("-X");
        panel2.add(xButton1);
        yButton = new JButton();
        yButton.setText("Y");
        panel2.add(yButton);
        yButton1 = new JButton();
        yButton1.setText("-Y");
        panel2.add(yButton1);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.CENTER);
        panel3.add(canvas3D, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
